#### 콘텐츠 기반 필터링

#### 협업 필터링
- 최근접 이웃 기반 협업필터링 
    - 사용자 기반 (현시점 가장 많이 사용됨)
    - 아이템 기반 
- 잠재요인 협업 필터링: 행렬 변환


In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
movies = pd.read_csv('./data/tmdb_5000_movies.csv')

In [12]:
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [13]:
movies.shape

(4803, 20)

In [18]:
movies_df = movies[['id','title','genres','vote_average','vote_count','popularity','keywords',\
                   'overview']]

In [19]:
movies_df.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                              genres  vote_average  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   
1        4500  139.082615  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2        4466  107.376788  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3        9106  112.312950  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4        2124   43.926995  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

#### 컨텐츠 기반 추천시스템 

In [21]:
movies_df['genres'][0]
# 장르 아이디, 이름

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [22]:
movies_df['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [27]:
# str로 된 python code를 실제 python code로 변환 :eval, literal_eval
type(movies_df['genres'][0])
#리스트에 딕셔너리가 있는것처럼 보이지만 문자로 되어있음.. 

str

In [37]:
from ast import literal_eval
literal_eval(movies_df['genres'][0])

type(literal_eval(movies_df['genres'][0]))

# 파이썬 객체로 바꿔주도록함 

ValueError: malformed node or string: [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]

In [38]:
movies_df['keywords']

0       [{"id": 1463, "name": "culture clash"}, {"id":...
1       [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2       [{"id": 470, "name": "spy"}, {"id": 818, "name...
3       [{"id": 849, "name": "dc comics"}, {"id": 853,...
4       [{"id": 818, "name": "based on novel"}, {"id":...
                              ...                        
4798    [{"id": 5616, "name": "united states\u2013mexi...
4799                                                   []
4800    [{"id": 248, "name": "date"}, {"id": 699, "nam...
4801                                                   []
4802    [{"id": 1523, "name": "obsession"}, {"id": 224...
Name: keywords, Length: 4803, dtype: object

In [40]:
movies_df['genres'] = movies_df['genres'].apply(literal_eval) 
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval) 

#컬럼전체에 함수적용 

C:\Users\bitcamp\AppData\Local\Temp/ipykernel_22756/3061771125.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)


In [41]:
movies_df['genres'][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [44]:
[d['name'] for d in movies_df['genres'][0]]
# 딕셔너리에서 네임부분만 필요하니까 네임만 뽑아보기
# 이 값을 장르에 넣을것임 

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [48]:
[d['name'] for d in movies_df['keywords'][0]]

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [49]:
movies_df['genres'] = movies_df['genres'].apply(lambda x: [d['name'] for d in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x: [d['name'] for d in x])
# 장르전체 적용, 키워드 전체 적용 

C:\Users\bitcamp\AppData\Local\Temp/ipykernel_22756/2021644211.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres'] = movies_df['genres'].apply(lambda x: [d['name'] for d in x])
C:\Users\bitcamp\AppData\Local\Temp/ipykernel_22756/2021644211.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['keywords'] = movies_df['keywords'].apply(lambda x: [d['name'] for d in x])


In [51]:
movies_df['genres']
movies_df['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...                        
4798    [united states–mexico barrier, legs, arms, pap...
4799                                                   []
4800    [date, love at first sight, narration, investi...
4801                                                   []
4802            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4803, dtype: object

In [52]:
movies_df.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                          genres  vote_average  vote_count  \
0  [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                   [Adventure, Fantasy, Action]           6.9        4500   
2                     [Action, Adventure, Crime]           6.3        4466   
3               [Action, Crime, Drama, Thriller]           7.6        9106   
4           [Action, Adventure, Science Fiction]           6.1        2124   

   popularity                                           keywords  \
0  150.437577  [culture clash, future, space war, space colon...   
1  139.082615  [ocean, drug abuse, exotic island, east india ...   
2  107.376788  [spy, based on novel, secret agent, sequel, mi...   
3  112.312950  [dc comics, crime fighter, terrorist, secret i...   
4   43.926995  [based on novel, mars, medallion, space travel...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [54]:
L = ['1','2','3','4','5']
' '.join(L)
# 리스트에있을땐 하나의 문자열이되는데 정수는 안됨 ex) L = [1,2,3,4,5]
    

'1 2 3 4 5'

In [65]:
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x: (' ').join(x))
# row에 적용이 될때 x(리스트)를 받아서 ' '를 통해 이어붙이게함 

C:\Users\bitcamp\AppData\Local\Temp/ipykernel_22756/2743708711.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres_literal'] = movies_df['genres'].apply(lambda x: (' ').join(x))


In [66]:
# count_vetorizer 를 쓰기 위해 이렇게함 (문자열을받음)
# 토큰을하고 벡터라이징을 하기위해 문자열로 바꿈 . .
# CountVectorizer에 넣기 위해서 문자열로 변환 

In [67]:
# # CountVectorizer: 문자열 => vector => sparse matrix
# #실제로 도큐먼트에 들어가는 토큰은 많지 않음.. 

#     # tok1, tok2, ....tok50000 
# doc1   1     0   0 0 0 ...2...  
# doc2   2     0   0 0 0...1 0..
# doc3 

In [68]:
# countvectorizer의 파라미터들을 구글링해서써도됨

In [75]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(min_df = 0, ngram_range=(1,2))
genres_mat = vect.fit_transform(movies_df['genres_literal'])

In [76]:
genres_mat.toarray()

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [77]:
genres_mat.toarray().shape

(4803, 276)

In [78]:
from sklearn.metrics.pairwise import cosine_similarity

In [79]:
genre_sim = cosine_similarity(genre_mat,genre_mat)

In [80]:
genre_sim

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [83]:
sim_idx = genre_sim[:10].argsort()[-10:]
#상위10개 

array([[2401, 3037, 3038, ...,  813, 3494,    0],
       [2401, 3067, 3069, ...,  129,    1,  262],
       [2401, 2999, 3000, ..., 1542, 1740,    2],
       ...,
       [2401, 3045, 3046, ...,   56, 2995,  102],
       [2401, 3124, 3125, ...,  276,  341,  191],
       [2401, 3067, 3069, ...,  107,   20,   38]], dtype=int64)

In [ ]:
movies_df.loc[sim_idx]

In [84]:
pd.DataFrame(genre_sim)

0         1         2         3         4         5     6     \
0     1.000000  0.596285  0.447214  0.125988  0.755929  0.596285   0.0   
1     0.596285  1.000000  0.400000  0.169031  0.338062  0.800000   0.0   
2     0.447214  0.400000  1.000000  0.338062  0.507093  0.600000   0.0   
3     0.125988  0.169031  0.338062  1.000000  0.142857  0.169031   0.0   
4     0.755929  0.338062  0.507093  0.142857  1.000000  0.507093   0.0   
...        ...       ...       ...       ...       ...       ...   ...   
4798  0.149071  0.200000  0.400000  0.676123  0.169031  0.200000   0.0   
4799  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   
4800  0.000000  0.000000  0.000000  0.125988  0.000000  0.000000   0.0   
4801  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   
4802  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   

          7         8         9     ...      4793      4794      4795  \
0     0.755929  0.447214  0.745356  ...  0.000000  0.000000  0.000000   
1     0.338062  0.600000  0.800000  ...  0.000000  0.000000  0.000000   
2     0.507093  0.200000  0.600000  ...  0.000000  0.000000  0.000000   
3     0.142857  0.000000  0.169031  ...  0.377964  0.169031  0.377964   
4     1.000000  0.169031  0.507093  ...  0.000000  0.000000  0.000000   
...        ...       ...       ...  ...       ...       ...       ...   
4798  0.169031  0.000000  0.200000  ...  0.000000  0.200000  0.000000   
4799  0.000000  0.000000  0.000000  ...  0.000000  0.258199  0.000000   
4800  0.000000  0.000000  0.000000  ...  0.333333  0.149071  0.333333   
4801  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
4802  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   

          4796      4797      4798    4799      4800  4801  4802  
0     0.377964  0.000000  0.149071  0.0000  0.000000   0.0   0.0  
1     0.000000  0.000000  0.200000  0.0000  0.000000   0.0   0.0  
2     0.000000  0.000000  0.400000  0.0000  0.000000   0.0   0.0  
3     0.428571  0.218218  0.676123  0.0000  0.125988   0.0   0.0  
4     0.428571  0.000000  0.169031  0.0000  0.000000   0.0   0.0  
...        ...       ...       ...     ...       ...   ...   ...  
4798  0.169031  0.258199  1.000000  0.0000  0.000000   0.0   0.0  
4799  0.000000  0.000000  0.000000  1.0000  0.384900   0.0   0.0  
4800  0.125988  0.000000  0.000000  0.3849  1.000000   0.0   0.0  
4801  0.000000  0.000000  0.000000  0.0000  0.000000   0.0   0.0  
4802  0.000000  0.000000  0.000000  0.0000  0.000000   0.0   1.0  

[4803 rows x 4803 columns]

In [86]:
genre_sim.argsort(axis=1)

array([[2401, 3037, 3038, ...,  813, 3494,    0],
       [2401, 3067, 3069, ...,  129,    1,  262],
       [2401, 2999, 3000, ..., 1542, 1740,    2],
       ...,
       [   0, 2230, 2229, ..., 1895, 3809, 4800],
       [   0, 3205, 3204, ..., 1596, 1594, 4802],
       [   0, 3141, 3140, ..., 4521, 4710, 4802]], dtype=int64)

In [87]:
genre_sim.argsort(axis=0)
# 매트릭스가 대칭구조임.. 

array([[2401, 2401, 2401, ...,    0,    0,    0],
       [3037, 3067, 2999, ..., 2230, 3205, 3141],
       [3038, 3069, 3000, ..., 2229, 3204, 3140],
       ...,
       [ 813,  129, 1542, ..., 1895, 1596, 4521],
       [3494,    1, 1740, ..., 3809, 1594, 4710],
       [   0,  262,    2, ..., 4800, 4802, 4802]], dtype=int64)

In [94]:
#유사도가 높은게 앞쪽으로 나오도록 
genre_sim_sorted_ind = genre_sim.argsort()[:,::-1] #스텝을 -1로 주면 역순으로 

# 컬럼값을 역순으로 정렬함 
# 자신이 가장 유사도가 높기때문에 맨처음은 0 

In [95]:
movie_index=50 
movies_df.loc[genre_sim_sorted_ind[movie_index[:5]]]

TypeError: 'int' object is not subscriptable

In [96]:
def find_sim_movie(df, sorted_ind, title_name, top_n = 0):
    
    title_movie = df[df['title'] == title_name] # 해당 영화 데이터 row 
    title_index = title_movie.index.values # 해당 영화의 index 
    
    similarity_indexes = sorted_ind[title_index, :(top_n)] 
    # sorted_ind matrix : row - 영화 인덱스 순서, columns - 유사도 순으로 영화인덱스가 올림차순 정렬 
    # sorted_ind: 유사도 matrix(해당영화row index, 왼쪽에서 n개 칼럼)
    
    similarity_indexes = similarity_indexes.reshape(-1)
    
    return df.iloc[similarity_indexes] # 유사도 높은 영화들의 데이터를 리턴 

In [97]:
df = movies_df

NameError: name 'find' is not defined